# Use custom format
format = '''
[┌───────────────────>](bold green)
[│](bold green)$directory$git_branch$git_status$git_state
[└─](bold green)$character '''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = '[λ](bold green) '
error_symbol = '[⚠](bold red) '

[git_branch]
symbol = '𣎴'
